version: '3.10'
services:
  web:
      build:
        context: .
        dockerfile: Dockerfile.prod
      command: gunicorn personal.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - static_data:/app/static
        - media_data:/app/media
      expose:
        - 8000
      restart: always
      # ports:
      #   - "8000:8000"
      env_file:
        - ./.env
      depends_on:
        - db
  db:
      image: postgres:13.0-alpine
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data:rw
      environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      # env_file:
      #   - .env.prod
  nginx:
      build: ./nginx
      volumes:
          - static_data:/app/static
          - media_data:/app/media
      ports:
          - "8008:80"
      depends_on:
          - web
volumes:
  media_data:
  static_data:
  postgres_data:      